version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/config"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "monthly"
