x-common-labels: &common-labels
  maintainer: "Parazeeknova"
  environment: "development"

x-common-deploy: &common-deploy
  resources:
    limits:
      memory: 1G
    reservations:
      memory: 512M

services:
  postgres-dev:
    container_name: zephyr-postgres-dev
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zephyr
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres-dev
      - DATABASE_URL=postgresql://postgres:postgres@%2Fvar%2Frun%2Fpostgresql/zephyr?schema=public
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@%2Fvar%2Frun%2Fpostgresql/zephyr?schema=public
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@%2Fvar%2Frun%2Fpostgresql/zephyr?schema=public
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - dev_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    labels:
      <<: *common-labels
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres -d zephyr"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  prisma-migrate:
    profiles: ["init"]
    container_name: zephyr-prisma-migrate
    image: node:18-alpine
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-dev:5432/zephyr?schema=public
      - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@postgres-dev:5432/zephyr?schema=public
      - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@postgres-dev:5432/zephyr?schema=public
    volumes:
      - ./packages/db:/app/packages/db
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    networks:
      - dev_network
    depends_on:
      postgres-dev:
        condition: service_healthy
    command: >
      sh -c "
      apk add --no-cache netcat-openbsd &&
      echo '⏳ Setting up Prisma...' &&
      npm install -g pnpm &&
      cd /app &&
      pnpm install --frozen-lockfile &&
      cd packages/db &&
      echo '⏳ Waiting for PostgreSQL...' &&
      until nc -z postgres-dev 5432; do
        echo 'Waiting for PostgreSQL to be ready...'
        sleep 2
      done &&
      echo '✅ PostgreSQL is ready' &&
      pnpm prisma db push --accept-data-loss &&
      echo '✅ Prisma migrations completed!'"

  redis-dev:
    container_name: zephyr-redis-dev
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - redis_data_dev:/data
    networks:
      - dev_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      <<: *common-labels
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-zephyrredis}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-dev:
    container_name: zephyr-minio-dev
    build:
      context: .
      dockerfile: ./docker/minio/Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
      - MINIO_ENABLE_OBJECT_LOCKING=on
    volumes:
      - minio_data_dev:/data
    networks:
      - dev_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      <<: *common-labels
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  minio-init:
    profiles: ["init"]
    image: minio/mc
    depends_on:
      minio-dev:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: >
      /bin/sh -c '
      echo "⏳ Waiting for MinIO..." &&
      sleep 5 &&
      mc config host add minio http://minio-dev:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      echo "✅ MinIO is ready" &&
      mc mb --ignore-existing minio/uploads &&
      mc anonymous set download minio/uploads &&
      mc version enable minio/uploads &&
      mc mb --ignore-existing minio/avatars &&
      mc anonymous set download minio/avatars &&
      mc version enable minio/avatars &&
      mc mb --ignore-existing minio/temp &&
      mc anonymous set download minio/temp &&
      mc version enable minio/temp &&
      mc mb --ignore-existing --with-lock minio/backups &&
      mc anonymous set download minio/backups &&
      mc version enable minio/backups &&
      echo "🎉 MinIO initialization completed!"
      '
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
    name: zephyr_dev_network
    labels:
      <<: *common-labels

volumes:
  postgres_data_dev:
    name: zephyr_postgres_data_dev
  redis_data_dev:
    name: zephyr_redis_data_dev
  minio_data_dev:
    name: zephyr_minio_data_dev
