[nix]
overlays = ["./.nixpacks/overlay.nix"]

[phases.setup]
nixPkgs = ["...", "nodejs_22", "prisma"]

[phases.install]
cmds = [
  "pnpm config set enable-pre-post-scripts true",
  "turbo telemetry disable",
  "pnpm install --frozen-lockfile --ignore-scripts"
]

[phases.build]
cmds = [
  "cd packages/db && pnpm dlx prisma generate",
  "NEXT_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_DISABLED=1 pnpm exec turbo build --filter=@zephyr/web... --force"
]

[start]
cmd = "cd apps/web && pnpm start"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_NO_CACHE = "1"

[environment]
NEXT_TELEMETRY_DISABLED = "1"
TURBO_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
PNPM_HOME = "/tmp/.pnpm"
