[phases.setup]
nixPkgs = ["nodejs@22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo build --filter=web..."]

[start]
cmd = "cd apps/web && node .next/standalone/apps/web/server.js"

# Environment variable defaults
[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
PORT = "3000"
