[nix]
overlays = ["./.nixpacks/overlay.nix"]

[phases.setup]
nixPkgs = ["...", "nodejs_22", "prisma", "bun", "turbo"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd packages/db && bunx prisma generate",
  "NEXT_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_DISABLED=1 bunx turbo build --filter=@zephyr/web... --force"
]

[start]
cmd = "cd apps/web && bun start"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NEXT_TELEMETRY_DISABLED = "1"
TURBO_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
