[phases.setup]
nixPkgs = ["nodejs", "bun", "openssl"]
workdir = "/app"

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx turbo build --filter=@zephyr/auth-app"]

[start]
cmd = "bun run start"
