name: Update Changelog

on:
  push:
    branches:
      - development
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Check skip condition
        id: skip-check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if echo "$COMMIT_MSG" | grep -iq "skip ci\|skip changelog"; then
            echo "Should skip this workflow"
            exit 78
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: development

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Extract commit information
        id: commit-info
        run: |
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          if [[ $COMMIT_MSG =~ ^([a-z]+)\[([^\]]+)\]:[[:space:]]*(.*)$ ]]; then
            TYPE=${BASH_REMATCH[1]}
            SCOPE=${BASH_REMATCH[2]}
            MESSAGE=${BASH_REMATCH[3]}
            
            case $TYPE in
              feat) TYPE="Features" ;;
              fix) TYPE="Bug Fixes" ;;
              docs) TYPE="Documentation" ;;
              style) TYPE="Styling" ;;
              refactor) TYPE="Code Refactoring" ;;
              perf) TYPE="Performance Improvements" ;;
              test) TYPE="Tests" ;;
              build) TYPE="Builds" ;;
              ci) TYPE="Continuous Integration" ;;
              chore) TYPE="Chores" ;;
              revert) TYPE="Reverts" ;;
              *) TYPE="Other Changes" ;;
            esac
            
            {
              echo "type=$TYPE"
              echo "message=$MESSAGE"
              echo "scope=$SCOPE"
            } >> $GITHUB_OUTPUT
          else
            echo "type=Other Changes" >> $GITHUB_OUTPUT
            echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
            echo "scope=" >> $GITHUB_OUTPUT
          fi

      - name: Update CHANGELOG.md
        run: |
          # Initialize CHANGELOG.md if it doesn't exist
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          
          DATE="${{ steps.date.outputs.date }}"
          TYPE="${{ steps.commit-info.outputs.type }}"
          MESSAGE="${{ steps.commit-info.outputs.message }}"
          SCOPE="${{ steps.commit-info.outputs.scope }}"
          
          # Create the new entry
          NEW_ENTRY="## [$DATE]\n### $TYPE\n"
          if [ ! -z "$SCOPE" ]; then
            NEW_ENTRY+="- $MESSAGE [$SCOPE]"
          else
            NEW_ENTRY+="- $MESSAGE"
          fi
          
          # Create a temporary file
          TEMP_FILE=$(mktemp)
          
          # Add header if file is empty
          if [ ! -s CHANGELOG.md ]; then
            echo -e "# Changelog\n\nAll notable changes to this project will be documented in this file.\n" > "$TEMP_FILE"
          else
            head -n 3 CHANGELOG.md > "$TEMP_FILE"
          fi
          
          # Add new entry
          echo -e "\n$NEW_ENTRY\n" >> "$TEMP_FILE"
          
          # Add the rest of the existing changelog
          if [ -s CHANGELOG.md ]; then
            tail -n +4 CHANGELOG.md >> "$TEMP_FILE"
          fi
          
          # Replace the original file
          mv "$TEMP_FILE" CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci] [skip changelog]"
          git push origin development
